version: '3.8'

services:
  backend:
    image: backend-image
    build:
      context: ./apps/backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    depends_on:
      - db

  frontend:
    image: frontend-image
    build:
      context: ./apps/frontend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"

  ui:
    image: ui-image
    build:
      context: ./apps/ui
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=production
    depends_on:
      - backend
